"""Stable enumerations used by the alarm domain."""

from enum import StrEnum


class AlarmPriority(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class AlarmState(StrEnum):
    INACTIVE = "INACTIVE"
    ACTIVE = "ACTIVE"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    CLEARED = "CLEARED"
    RESET = "RESET"


class AlarmAction(StrEnum):
    TRIGGER = "TRIGGER"
    ACKNOWLEDGE = "ACKNOWLEDGE"
    CLEAR = "CLEAR"
    RESET = "RESET"
    FINALIZE = "FINALIZE"


class AlarmEventType(StrEnum):
    ACTIVATED = "ALARM_ACTIVATED"
    ACKNOWLEDGED = "ALARM_ACKNOWLEDGED"
    CLEARED = "ALARM_CLEARED"
    RESET = "ALARM_RESET"
    FINALIZED = "ALARM_FINALIZED"
    REACTIVATED = "ALARM_REACTIVATED"
    DUPLICATE_DETECTED = "DUPLICATE_DETECTED"
    SUPPRESSED = "ALARM_SUPPRESSED"
    UNSUPPRESSED = "ALARM_UNSUPPRESSED"
    ESCALATED = "ALARM_ESCALATED"
